# -----------------------------------------------------------------------------
# installer
# -----------------------------------------------------------------------------
FROM melonproject/node:latest

# Copy whole workspace into the container. This seems crazy but
# is actually more efficient than copying each package.json
# individually.
COPY . /app

RUN yarn install --ignore-engines --frozen-lockfile --pure-lockfile
