# -----------------------------------------------------------------------------
# base
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as base
WORKDIR /app

# Install system dependencies.
RUN apk add --update --no-cache --virtual .apk git python make g++

# -----------------------------------------------------------------------------
# installer
# -----------------------------------------------------------------------------
FROM base as installer

# Copy whole workspace into the container. This seems crazy but
# is actually more efficient than copying each package.json
# individually.
COPY . /app

# Install node dependencies and clean up afterwards.
RUN yarn install --ignore-engines --frozen-lockfile --pure-lockfile --production && \
  cp -R node_modules node_modules_production && \
  yarn install --ignore-engines --frozen-lockfile --pure-lockfile && \
  yarn cache clean && \
  apk del .apk
