export const types = {
  SET: "SET:fund:melon.fund",
  INFO_REQUESTED: "INFO_REQUESTED:fund:melon.fund",
  INFO_SUCCEEDED: "INFO_SUCCEEDED:fund:melon.fund",
  INFO_FAILED: "INFO_FAILED:fund:melon.fund",
  SHARE_PRICE_REQUESTED: "SHARE_PRICE_REQUESTED:fund:melon.fund",
  SHARE_PRICE_SUCCEEDED: "SHARE_PRICE_SUCCEEDED:fund:melon.fund",
  SHARE_PRICE_FAILED: "SHARE_PRICE_FAILED:fund:melon.fund",
  SETUP_REQUESTED: "SETUP_REQUESTED:fund:melon.fund",
  SETUP_SUCCEEDED: "SETUP_SUCCEEDED:fund:melon.fund",
  SETUP_FAILED: "SETUP_FAILED:fund:melon.fund",
  UPDATE_RANKING: "UPDATE_RANKING:fund:melon.fund",
  SET_PENDING_REQUEST: "SET_PENDING_REQUEST:fund:melon.fund",
  READY_TO_EXECUTE: "READY_TO_EXECUTE:fund:melon.fund",
  SET_LOADING: "SET_LOADING:fund:melon.fund",
};

export const actions = {
  set: address => ({
    type: types.SET,
    address,
  }),
  setupRequested: name => ({
    type: types.SETUP_REQUESTED,
    name,
  }),
  setupSucceeded: ({ id, address, name, timestamp, owner }) => ({
    type: types.SETUP_SUCCEEDED,
    id,
    address,
    name,
    timestamp,
    owner,
  }),
  setupFailed: ({ reason }) => ({
    type: types.SETUP_FAILED,
    reason,
  }),
  infoRequested: address => ({
    type: types.INFO_REQUESTED,
    address,
  }),
  infoFailed: ({ reason }) => ({
    type: types.INFO_FAILED,
    reason,
  }),
  infoSucceeded: ({
    address,
    aum,
    creationDate,
    gav,
    managementReward,
    name,
    nav,
    owner,
    performanceReward,
    personalStake,
    sharePrice,
    totalSupply,
    unclaimedRewards,
    subscriptionAllowed,
    redemptionAllowed,
    inception,
    loading,
  }) => ({
    type: types.INFO_SUCCEEDED,
    address,
    aum,
    creationDate,
    gav,
    managementReward,
    name,
    nav,
    owner,
    performanceReward,
    personalStake,
    redemptionAllowed,
    sharePrice,
    subscriptionAllowed,
    totalSupply,
    unclaimedRewards,
    inception,
    loading,
  }),
  sharePriceRequested: () => ({
    type: types.SHARE_PRICE_REQUESTED,
  }),
  sharePriceFailed: ({ reason }) => ({
    type: types.SHARE_PRICE_FAILED,
    reason,
  }),
  sharePriceSucceeded: ({ sharePrice }) => ({
    type: types.SHARE_PRICE_SUCCEEDED,
    sharePrice,
  }),
  updateRanking: ({ rank, numberOfFunds }) => ({
    type: types.UPDATE_RANKING,
    rank,
    numberOfFunds,
  }),
  setPendingRequest: pendingRequest => ({
    type: types.SET_PENDING_REQUEST,
    pendingRequest,
    readyToExecute: false,
  }),
  setReadyToExecute: () => ({
    type: types.READY_TO_EXECUTE,
    readyToExecute: true,
  }),
  setLoading: address => ({
    type: types.SET_LOADING,
    address,
  }),
};
