export const types = {
  SET: "SET:fund:melon.fund",
  INFO_REQUESTED: "INFO_REQUESTED:fund:melon.fund",
  INFO_SUCCEEDED: "INFO_SUCCEEDED:fund:melon.fund",
  INFO_FAILED: "INFO_FAILED:fund:melon.fund",
  SETUP_REQUESTED: "SETUP_REQUESTED:fund:melon.fund",
  SETUP_SUCCEEDED: "SETUP_SUCCEEDED:fund:melon.fund",
  SETUP_FAILED: "SETUP_FAILED:fund:melon.fund",
};

export const actions = {
  set: address => ({
    type: types.SET,
    address,
  }),
  setupRequested: name => ({
    type: types.SETUP_REQUESTED,
    name,
  }),
  setupSucceeded: ({ id, address, name, timestamp, owner }) => ({
    type: types.SETUP_SUCCEEDED,
    id,
    address,
    name,
    timestamp,
    owner,
  }),
  setupFailed: ({ reason }) => ({
    type: types.SETUP_FAILED,
    reason,
  }),
  infoRequested: address => ({
    type: types.INFO_REQUESTED,
    address,
  }),
  infoFailed: ({ reason }) => ({
    type: types.INFO_FAILED,
    reason,
  }),
  infoSucceeded: ({
    address,
    aum,
    creationDate,
    gav,
    managementReward,
    name,
    nav,
    owner,
    performanceReward,
    personalStake,
    sharePrice,
    totalSupply,
    unclaimedRewards,
    subscriptionAllowed,
    redemptionAllowed,
  }) => ({
    type: types.INFO_SUCCEEDED,
    address,
    aum,
    creationDate,
    gav,
    managementReward,
    name,
    nav,
    owner,
    performanceReward,
    personalStake,
    redemptionAllowed,
    sharePrice,
    subscriptionAllowed,
    totalSupply,
    unclaimedRewards,
  }),
};
